/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@import Cocoa;

@class NSTitlebarContainerView, NSTitlebarView;

@interface NSThemeFrame : NSView

@property (readonly) NSTitlebarContainerView *titlebarContainerView;
@property (strong) NSTitlebarView *titlebarView;

- (void)mouseExitedLeftButtonGroup;
- (void)mouseEnteredLeftButtonGroup;
- (NSRect)leftButtonGroupFrameInTitlebarView;
- (id)_titleTextField;

@end

