/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@import Cocoa;

@interface NSTitlebarView : NSVisualEffectView

@property BOOL transparent;

- (id)titleFont;
- (id)menuForEvent:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)_removeTrackingAreaIfNeeded;
- (id)associatedThemeFrame;
@property BOOL drawsSeparator;
- (void)dealloc;
- (id)initWithFrame:(NSRect *)frameRect;

@end

